name: 'Issue tracker mm-bot'

on:
  workflow_dispatch:

  issues:
    types: [opened, edited, deleted, closed, reopened]
  issue_comment: 
    types: [created, edited, deleted]
  pull_request:
    types: [opened, edited, closed, reopened]
    branches: [main]
  
jobs:
  summary_issue:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "{" >> mattermost.json
          echo "\"text\": \"testing github action :tada:\"" >> mattermost.json
          echo "}" >> mattermost.json
      - uses: mattermost/action-mattermost-notify@master
        env:
          MATTERMOST_WEBHOOK_URL: "https://mattermost.web.cern.ch/hooks/5b4ab1kgdtdete87bghxebcdgy"          
