name: 'Issue tracker mm-bot'

on:
  workflow_dispatch:

  issues:
    #types: [opened, edited, deleted, closed, reopened]
    types: [opened, edited, deleted, reopened]
  issue_comment: 
    types: [created, edited]
  #pull_request:
  #  types: [opened, edited, closed, reopened]
  #  branches: [main]
  
jobs:
  notify_issue:
    runs-on: ubuntu-latest
    if: ${{ !github.event.issue_comment }}
    steps:
      - name: mattermost-notify
        uses: mattermost/action-mattermost-notify@master
        with:
          MATTERMOST_WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
          MATTERMOST_USERNAME: ${{ vars.MATTERMOST_USERNAME }}
          MATTERMOST_ICON_URL: ${{ vars.MATTERMOST_ICON }}
          TEXT: |-
            :github: Issue at CPNR-computing is ${{ github.event.type }}
            - Title: ${{ github.event.issue.title }}"
            - URL: ${{ github.event.issue.html_url }}"
            Content: ${{ github.event.issue.body }}
  notify_comment:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue_comment }}
    steps:
      - uses: mattermost/action-mattermost-notify@master
        with:
          MATTERMOST_WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
          MATTERMOST_USERNAME: ${{ vars.MATTERMOST_USERNAME }}
          MATTERMOST_ICON_URL: ${{ vars.MATTERMOST_ICON }}
          TEXT: |-
            :github: Comment in issue at CPNR-computing is ${{ github.event.type }}
            - Title: ${{ github.event.issue.title }}
            - URL: ${{ github.event.issue.html_url }}
            Comment: ${{ github.event.comment.body }}
