name: 'Issue tracker mm-bot'

on:
  workflow_dispatch:

  issues:
    #types: [opened, edited, deleted, closed, reopened]
    types: [opened, edited, deleted, reopened]
  issue_comment: 
    types: [created, edited]
  pull_request:
    types: [opened, edited, closed, reopened]
    branches: [main]
  
jobs:
  monitor_issue:
    runs-on: ubuntu-latest
    steps:
      - run: |
          IMOJI=":github":
          TEXT="$IMOJI Update in issue at CPNR-computing"
          TEXT="$TEXT\n- Title: ${{ github.event.issue.title }}"
          TEXT="$TEXT\n- URL: ${{ github.event.issue.html_url }}"
          echo -ne '{"text":"' >> mattermost.json
          echo -ne "$TEXT" >> mattermost.json
          echo -ne '"}' >> mattermost.json
          cat mattermost.json
      - uses: mattermost/action-mattermost-notify@master
        env:
          MATTERMOST_WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
          MATTERMOST_USERNAME: "cpnr-computing"
          MATTERMOST_ICON: "https://avatars.githubusercontent.com/u/70711208?s=400&u=65f046741488f22be7ba197426339f6d8311b69f&v=4"
