name: 'Issue tracker mm-bot'

on:
  workflow_dispatch:

  issues:
    #types: [opened, edited, deleted, closed, reopened]
    types: [opened, edited, deleted, reopened]
  issue_comment: 
    types: [created, edited]
  #pull_request:
  #  types: [opened, edited, closed, reopened]
  #  branches: [main]
  
jobs:
  test_secrets:
    runs-on: ubuntu-latest
    steps:
      - name: test_secrets
        run: |
          echo -ne "From action ${{ vars.MATTERMOST_USERNAME }}"
          echo -ne "${{ github.event }}"
          echo -ne "${{ secrets.MATTERMOST_WEBHOOK_URL }}"
  monitor_issue:
    runs-on: ubuntu-latest
    steps:
      - name: mm_setup
        run: |
          IMOJI=":github":
          TEXT="$IMOJI Update in issue at CPNR-computing"
          TEXT="$TEXT\n- Title: ${{ github.event.issue.title }}"
          TEXT="$TEXT\n- URL: ${{ github.event.issue.html_url }}"
          echo -ne '{"text":"' >> mattermost.json
          echo -ne "$TEXT" >> mattermost.json
          echo -ne '"}' >> mattermost.json
          cat mattermost.json
      - uses: mattermost/action-mattermost-notify@master
        with:
          MATTERMOST_WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
          MATTERMOST_USERNAME: ${{ vars.MATTERMOST_USERNAME }}
          MATTERMOST_ICON: ${{ vars.MATTERMOST_ICON }}
